### ISSUE TITLE
lost search interface

### ISSUE THREAD

**Issue by lvscar** [GitbookIO/theme-default#24]
copy layouts/website  from  "theme-default"  to my gitbook  _layout  directory  ,  then using  `gitbook build`  building my book.   the final result webpage  lost search input interface .

theme-default version:   ( master  branch and  1.0.4 tag )
gitbook version:   3.1.1

**Comment by LionelCons** [comment]
Same here with theme-default master and GitBook 3.2.0 :-(

**Comment by SamyPesse** [comment]
Why did you copy the folder?

This is not the right method to extend the default theme.

You can create a file `_layouts/website/page.html`, which extends the default theme:

```html
{% extends template.self %}

{% block book_navigation %}
      <b>Test</b>
{% endblock %}
```

**Comment by LionelCons** [comment]
I did copy the folder because I wanted to modify the summary and summary.html does not have any block to override.
