### ISSUE TITLE
Theme is not the same as README screenshot, missing features

### ISSUE THREAD

**Issue by jayphelps** [GitbookIO/theme-default#25]
Ever since gitbook 3.0 it appears the theme is missing some of the old features which made gitbook better than using standard GH pages, such as numbering the chapters, read progress, etc.

I searched pretty extensively and cannot find anyone else commenting on this or any plans to add these old features back.

http://redux-observable.github.io/redux-observable/

![image](https://cloud.githubusercontent.com/assets/762949/16786307/a88dbd66-4848-11e6-8ef0-3af8b931dc3a.png)

Is there a way to use the old theme with gitbook 3.0?

**Comment by SamyPesse** [comment]
Sorry for late response,

Numbering can be enabled with:

```js
{
    "pluginsConfig": {
         "theme-default": {
             "showLevel": true
         }
    }
}
```

Read progress has been removed, and can be implemented as an external plugin (I'll try to do it as soon as I have free time, we are working on big improvements for gitbook.com and the editor).
