### ISSUE TITLE
Source for Night theme? 

### ISSUE THREAD

**Issue by kevinSuttle** [GitbookIO/theme-default#29]
Can't seem to find those anywhere. Where should I look?

**Comment by jpreynat** [comment]
Hi @kevinSuttle,

The default theme only integrate the CSS for the default (white) theme.
The LESS sources for the sepia and night themes are located in the [plugin-fontsettings](https://github.com/GitbookIO/plugin-fontsettings) repo.

In the source code, they are named respectively:
- sepia: `color-theme-1`
- night: `color-theme-2`
