### ISSUE TITLE
eBook : Title is duplicated

### ISSUE THREAD

**Issue by borisschapira** [GitbookIO/theme-default#4]
On the eBook, the title is "duplicated" : in fact, the page first render the title coming from SUMMARY.md and then, the main title coming from the file itself.

**Comment by SamyPesse** [comment]
I cannot reproduce this issue, which version of GitBook are you using ? (this theme is only for `>=3.0.0`).

**Comment by borisschapira** [comment]
Hi, that explains it. I was using an older version (the default version installed with gitbook-cli, the 2.4… something). Sorry for the inconvenience, I switched to 2.6.7 since then and does not encounter the bug anymore (I got the advice from Slack).
